modLoader="javafml" #mandatory
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/OneLemonyBoi/XLFoodMod/issues" #optional
license = "GNU"
[[mods]] #mandatory
modId="xlfoodmod" #mandatory
version="${version}"
displayName="XL Food Mod" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/xl-food-mod-plus" #optional
logoFile="" #optional
authors="OneLemonyBoi" #optional
description='''
A mod that adds more foods and crops to the game.
'''

[[dependencies.xlfoodmod]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version}]"
side="BOTH"

[[dependencies.xlfoodmod]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
side="BOTH"
